### ISSUE TITLE
Error when I compile MoeingEVM

### ISSUE THREAD

**Issue by SKlayer** [smartbch/MoeingEVM#1]
make[1]: 进入目录“/home/dev/桌面/moeing/MoeingEVM/evmwrap/host_bridge”
g++ -Wall -O3 -fPIC -std=c++17 -c -I ../evmone/include/ -I ../evmc/include/ -I ../intx/include/ -I ../keccak/include -o host_context.o -c host_context.cpp
host_context.cpp:100:1: error: designator order for field ‘evmc_host_interface::call’ does not match declaration order in ‘evmc_host_interface’
  100 | };
      | ^
host_context.cpp: In member function ‘size_t evmc_host_context::get_code_size(const evmc_address&)’:

**Comment by wangkui0508** [comment]
This error is caused by the different compilers used by cgo in MacOS and Ubuntu. Now it is fixed.
